$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: temp-forecast-online-endpoint
model: azureml:temp-forecast-best-model:1
instance_type: Standard_E2s_v3
instance_count: 1
