$schema: https://azuremlschemas.azureedge.net/latest/autoMLClassificationJob.schema.json
type: automl

name: diabetes-job-20260320043854
experiment_name: diabetes-exp-20260320043854

compute: azureml:f4s-v2-cpu-cluster

task: classification
primary_metric: accuracy

training_data:
  type: mltable
  path: azureml:diabetes-data:20260320043836

target_column_name: Diabetic

limits:
  max_trials: 8
  max_concurrent_trials: 2
  timeout_minutes: 60
  trial_timeout_minutes: 50
  enable_early_termination: true

featurization:
  mode: auto
